const UserExample = {
  avatar_url: "https://example.com/avatar.jpg",
  id: 123456,
  kind: "user",
  permalink_url: "https://example.com/user123",
  uri: "https://api.example.com/users/123456",
  username: "user123",
  permalink: "user123",
  created_at: "2024-01-01T12:00:00Z",
  last_modified: "2024-02-01T12:00:00Z",
  first_name: "John",
  last_name: "Doe",
  full_name: "John Doe",
  city: "Kyiv",
  description: "Music lover and sound enthusiast",
  country: "Ukraine",
  track_count: 10,
  public_favorites_count: 5,
  reposts_count: 2,
  followers_count: 100,
  followings_count: 50,
  plan: "Pro",
  myspace_name: null,
  discogs_name: null,
  website_title: "John's Music",
  website: "https://johnmusic.com",
  comments_count: 15,
  online: true,
  likes_count: 25,
  playlist_count: 3,
  subscriptions: [],
};

const TrackExample = {
  kind: "track",
  id: 654321,
  created_at: "2024-01-01T12:00:00Z",
  duration: 300000,
  commentable: true,
  comment_count: 20,
  sharing: "public",
  tag_list: "electronic, chill",
  streamable: true,
  embeddable_by: "all",
  purchase_url: "https://example.com/purchase",
  purchase_title: "Buy Track",
  genre: "Electronic",
  title: "Chill Vibes",
  description: "A relaxing electronic track to unwind to.",
  label_name: null,
  release: null,
  key_signature: null,
  isrc: "US1234567890",
  bpm: null,
  release_year: null,
  release_month: null,
  release_day: null,
  license: "all-rights-reserved",
  uri: "https://api.example.com/tracks/654321",
  user: UserExample,
  permalink_url: "https://example.com/track654321",
  artwork_url: "https://example.com/artwork.jpg",
  stream_url: "https://example.com/stream",
  download_url: null,
  waveform_url: "https://example.com/waveform",
  available_country_codes: null,
  secret_uri: null,
  user_favorite: null,
  user_playback_count: null,
  playback_count: 5000,
  download_count: 200,
  favoritings_count: 1000,
  reposts_count: 100,
  downloadable: true,
  access: "public",
  policy: null,
  monetization_model: null,
};
const TrackListExample = {
  duration: 300000,
  genre: "Electronic",
  release_day: null,
  permalink: "chill-vibes-playlist",
  permalink_url: "https://example.com/playlists/chill-vibes",
  release_month: null,
  release_year: null,
  description: "A playlist full of relaxing and chill electronic tracks.",
  uri: "https://api.example.com/playlists/789",
  label_name: "Chill Label",
  label_id: null,
  label: null,
  tag_list: "chill, electronic, vibes",
  track_count: 2,
  user_id: 123456,
  last_modified: "2024-02-01T12:00:00Z",
  license: "all-rights-reserved",
  user: UserExample,
  playlist_type: "playlist",
  type: "playlist",
  id: 789,
  downloadable: null,
  likes_count: 500,
  sharing: "public",
  created_at: "2024-01-01T12:00:00Z",
  release: null,
  tags: "chill, vibes",
  kind: "playlist",
  title: "Chill Vibes Playlist",
  purchase_title: "Buy Playlist",
  ean: "1234567890123",
  streamable: true,
  embeddable_by: "all",
  artwork_url: "https://example.com/playlist-artwork.jpg",
  purchase_url: "https://example.com/buy-playlist",
  tracks_uri: "https://api.example.com/playlists/789/tracks",
  tracks: [TrackExample],
};

export {UserExample,TrackExample,TrackListExample}
